# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameResults = QtWidgets.QFrame(self.centralwidget)
        self.frameResults.setGeometry(QtCore.QRect(10, 10, 1001, 71))
        self.frameResults.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameResults.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameResults.setObjectName("frameResults")
        self.textVolume = QtWidgets.QLineEdit(self.frameResults)
        self.textVolume.setGeometry(QtCore.QRect(10, 0, 71, 31))
        self.textVolume.setReadOnly(True)
        self.textVolume.setObjectName("textVolume")
        self.textPrice = QtWidgets.QLineEdit(self.frameResults)
        self.textPrice.setGeometry(QtCore.QRect(10, 40, 71, 31))
        self.textPrice.setReadOnly(True)
        self.textPrice.setObjectName("textPrice")
        self.frameScope = QtWidgets.QFrame(self.centralwidget)
        self.frameScope.setGeometry(QtCore.QRect(10, 90, 141, 251))
        self.frameScope.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameScope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameScope.setObjectName("frameScope")
        self.label = QtWidgets.QLabel(self.frameScope)
        self.label.setGeometry(QtCore.QRect(10, 0, 60, 16))
        self.label.setObjectName("label")
        self.slideScope = QtWidgets.QSlider(self.frameScope)
        self.slideScope.setGeometry(QtCore.QRect(10, 200, 121, 22))
        self.slideScope.setMaximum(50)
        self.slideScope.setOrientation(QtCore.Qt.Horizontal)
        self.slideScope.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideScope.setObjectName("slideScope")
        self.buttonScope = QtWidgets.QPushButton(self.frameScope)
        self.buttonScope.setGeometry(QtCore.QRect(0, 220, 141, 32))
        self.buttonScope.setObjectName("buttonScope")
        self.listScope = QtWidgets.QTableWidget(self.frameScope)
        self.listScope.setEnabled(True)
        self.listScope.setGeometry(QtCore.QRect(10, 20, 121, 181))
        self.listScope.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listScope.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listScope.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listScope.setObjectName("listScope")
        self.listScope.setColumnCount(0)
        self.listScope.setRowCount(0)
        self.listScope.horizontalHeader().setVisible(False)
        self.listScope.verticalHeader().setVisible(False)
        self.frameCsp = QtWidgets.QFrame(self.centralwidget)
        self.frameCsp.setGeometry(QtCore.QRect(10, 350, 141, 141))
        self.frameCsp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCsp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCsp.setObjectName("frameCsp")
        self.label_3 = QtWidgets.QLabel(self.frameCsp)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 60, 16))
        self.label_3.setObjectName("label_3")
        self.buttonCsp = QtWidgets.QPushButton(self.frameCsp)
        self.buttonCsp.setGeometry(QtCore.QRect(0, 110, 141, 32))
        self.buttonCsp.setObjectName("buttonCsp")
        self.slideCsp = QtWidgets.QSlider(self.frameCsp)
        self.slideCsp.setGeometry(QtCore.QRect(10, 90, 121, 22))
        self.slideCsp.setMaximum(50)
        self.slideCsp.setOrientation(QtCore.Qt.Horizontal)
        self.slideCsp.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideCsp.setObjectName("slideCsp")
        self.listCsp = QtWidgets.QTableWidget(self.frameCsp)
        self.listCsp.setGeometry(QtCore.QRect(10, 20, 121, 71))
        self.listCsp.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listCsp.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listCsp.setObjectName("listCsp")
        self.listCsp.setColumnCount(0)
        self.listCsp.setRowCount(0)
        self.listCsp.horizontalHeader().setVisible(False)
        self.listCsp.verticalHeader().setVisible(False)
        self.frameCountry = QtWidgets.QFrame(self.centralwidget)
        self.frameCountry.setGeometry(QtCore.QRect(850, 90, 161, 401))
        self.frameCountry.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCountry.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCountry.setObjectName("frameCountry")
        self.label_2 = QtWidgets.QLabel(self.frameCountry)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 60, 16))
        self.label_2.setObjectName("label_2")
        self.listCountry = QtWidgets.QTableWidget(self.frameCountry)
        self.listCountry.setGeometry(QtCore.QRect(10, 20, 141, 331))
        self.listCountry.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listCountry.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listCountry.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listCountry.setObjectName("listCountry")
        self.listCountry.setColumnCount(0)
        self.listCountry.setRowCount(0)
        self.listCountry.horizontalHeader().setVisible(False)
        self.listCountry.verticalHeader().setVisible(False)
        self.buttonCountry = QtWidgets.QPushButton(self.frameCountry)
        self.buttonCountry.setGeometry(QtCore.QRect(0, 370, 161, 32))
        self.buttonCountry.setObjectName("buttonCountry")
        self.slideCountry = QtWidgets.QSlider(self.frameCountry)
        self.slideCountry.setGeometry(QtCore.QRect(10, 350, 141, 22))
        self.slideCountry.setMinimum(-100)
        self.slideCountry.setMaximum(500)
        self.slideCountry.setSingleStep(10)
        self.slideCountry.setPageStep(100)
        self.slideCountry.setSliderPosition(0)
        self.slideCountry.setOrientation(QtCore.Qt.Horizontal)
        self.slideCountry.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slideCountry.setTickInterval(100)
        self.slideCountry.setObjectName("slideCountry")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 90, 681, 401))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.listCompany = QtWidgets.QTableWidget(self.frame)
        self.listCompany.setGeometry(QtCore.QRect(5, 21, 671, 371))
        self.listCompany.setObjectName("listCompany")
        self.listCompany.setColumnCount(0)
        self.listCompany.setRowCount(0)
        self.listCompany.horizontalHeader().setSortIndicatorShown(True)
        self.listCompany.verticalHeader().setVisible(False)
        self.listCompany.verticalHeader().setHighlightSections(False)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 60, 16))
        self.label_4.setObjectName("label_4")
        self.goButton = QtWidgets.QPushButton(self.centralwidget)
        self.goButton.setGeometry(QtCore.QRect(160, 500, 113, 32))
        self.goButton.setObjectName("goButton")
        self.countryButton = QtWidgets.QPushButton(self.centralwidget)
        self.countryButton.setGeometry(QtCore.QRect(290, 500, 113, 32))
        self.countryButton.setObjectName("countryButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Scope"))
        self.buttonScope.setText(_translate("MainWindow", "RAZ"))
        self.label_3.setText(_translate("MainWindow", "Csp"))
        self.buttonCsp.setText(_translate("MainWindow", "RAZ"))
        self.label_2.setText(_translate("MainWindow", "Country"))
        self.buttonCountry.setText(_translate("MainWindow", "RAZ"))
        self.label_4.setText(_translate("MainWindow", "Company"))
        self.goButton.setText(_translate("MainWindow", "bridge"))
        self.countryButton.setText(_translate("MainWindow", "country"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

